### ISSUE TITLE
Pyface Bugfix Release 7.0.1

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#557]
Target date: To be confirmed, will edit here once confirmed.

This is a bug fix release and therefore the procedure will be slightly different compared to a major/minor release.
See https://github.com/enthought/traitsui/issues/933 for TraitsUI bugfix release 7.0.1.

Pre-release
---
- [x] Verify PRs that need to be merged to the maintanence branch are included in the Release 7.0.1 milestone
- [x] Create a PR with cherry picked changes and target the `maint/7.0` branch, review and merge (#562)
- [x] Test against other ETS packages and other pyface-using projects
- [x] Update changelog and open PR targeting `maint/7.0` branch  (#562)
- [x] Check MANIFEST and requirements are still up to date.
- [x] Test building the documentation

Release
--------
- [x] Create PR targeting `maint/7.0` branch. In this PR: (#580  )
        - Set release to `7.0.1`, and set `IS_RELEASED` is true; commit
        - Bump the version to `7.0.2` and set `IS_RELEASED` to false; commit
- [x] From the commit at which `IS_RELEASED` is true and version is `7.0.1`, create a release branch `release/7.0.1` from the `maint/7.0` branch; push (Edited post-release: in retrospect, this step may not be necessary)
- [x] On the release commit, add an annotated tag, and push the tag
- [x] Make PR targeting `gh-pages` branch: Generate documentation and copy the content to the branch. Verify that the resulting docs/index.html looks good. See https://github.com/enthought/pyface/pull/503 for a similar PR (#583)
- [x] Install from source distribution and run tests again
- [x] Upload to PyPI
- [x] Test the PyPI package
- [x] Announcement

Post-release
-------------
- [x] Package update for `enthought/free` repository (for EDM)
- [x] Backport release note and change log to master, and possibly `maint/7.0` branch (#578 )

**Comment by kitchoi** [comment]
Updated steps to be consistent with past practices in this project.

**Comment by rahulporuri** [comment]
closing as all of the tasks in the release checklist are now complete.
